#include "keymap.h"
#include <ctype.h>

typedef struct {
  nogui_keycode_t key;
  const char* value;
} nogui_keyname_t;

// Sorted Array for Lookup Key Names
const static nogui_keyname_t nogui_keyname_table[];

// -----------------------------
// Keycode Special String Lookup
// -----------------------------

static const char* nogui_keyname_lookup(nogui_keycode_t keycode) {
  const int size = 92;

  int left = 0;
  int right = size - 1;

  while (left <= right) {
    int mid = left + (right - left) / 2;
    nogui_keycode_t k = nogui_keyname_table[mid].key;

    // Keycode Found?
    if (k == keycode)
      return nogui_keyname_table[mid].value;

    // Step Half
    if (k < keycode)
      left = mid + 1;
    else right = mid - 1;
  }

  // Not Platform Independent
  return "Unknown";
}

const char* nogui_keycode_name(nogui_keycode_t keycode) {
  static char ascii[2] = {'\0', '\0'};
  // Check if is an ASCII Keycode
  if (keycode > 32 && keycode < 0xFF) {
    ascii[0] = (char) toupper(keycode);
    return &ascii;
  }

  // Lookup Special Keycode
  return nogui_keyname_lookup(keycode);
}

// -----------------------------
// Keycode Special String Naming
// Generated by keymap/keymap.py
// -----------------------------

const static nogui_keyname_t nogui_keyname_table[] = {
  {0, "Unknown"},
  {1, "Mouse Left"},
  {2, "Mouse Right"},
  {3, "Mouse Middle"},
  {4, "Mouse EX1"},
  {5, "Mouse EX2"},
  {32, "Space"},
  {65027, "AltGr"},
  {65056, "Left Tab"},
  {65288, "Backspace"},
  {65289, "Tab"},
  {65293, "Return"},
  {65299, "Pause"},
  {65300, "Scroll Lock"},
  {65301, "Sys Req"},
  {65307, "Escape"},
  {65360, "Home"},
  {65361, "Left"},
  {65362, "Up"},
  {65363, "Right"},
  {65364, "Down"},
  {65365, "Page Up"},
  {65366, "Page Down"},
  {65367, "End"},
  {65368, "Begin"},
  {65376, "Select"},
  {65377, "Print"},
  {65378, "Execute"},
  {65379, "Insert"},
  {65381, "Undo"},
  {65382, "Redo"},
  {65383, "Menu"},
  {65384, "Find"},
  {65385, "Cancel"},
  {65386, "Help"},
  {65387, "Break"},
  {65408, "Numpad Space"},
  {65417, "Numpad Tab"},
  {65421, "Numpad Enter"},
  {65429, "Numpad Home"},
  {65430, "Numpad Left"},
  {65431, "Numpad Up"},
  {65432, "Numpad Right"},
  {65433, "Numpad Down"},
  {65434, "Numpad PageUp"},
  {65435, "Numpad PageDown"},
  {65436, "Numpad End"},
  {65437, "Numpad Begin"},
  {65438, "Numpad Insert"},
  {65439, "Numpad Delete"},
  {65450, "Numpad Multiply"},
  {65451, "Numpad App"},
  {65452, "Numpad Separator"},
  {65453, "Numpad Substract"},
  {65454, "Numpad Decimal"},
  {65455, "Numpad Divide"},
  {65456, "Numpad 0"},
  {65457, "Numpad 1"},
  {65458, "Numpad 2"},
  {65459, "Numpad 3"},
  {65460, "Numpad 4"},
  {65461, "Numpad 5"},
  {65462, "Numpad 6"},
  {65463, "Numpad 7"},
  {65464, "Numpad 8"},
  {65465, "Numpad 9"},
  {65469, "Numpad Equal"},
  {65470, "F1"},
  {65471, "F2"},
  {65472, "F3"},
  {65473, "F4"},
  {65474, "F5"},
  {65475, "F6"},
  {65476, "F7"},
  {65477, "F8"},
  {65478, "F9"},
  {65479, "F10"},
  {65480, "F11"},
  {65481, "F12"},
  {65505, "Shift"},
  {65506, "Right Shift"},
  {65507, "Control"},
  {65508, "Right Control"},
  {65509, "Caps Lock"},
  {65510, "Shift Lock"},
  {65511, "Meta"},
  {65512, "Right Meta"},
  {65513, "Alt"},
  {65514, "Right Alt"},
  {65515, "Super"},
  {65516, "Super Right"},
  {65535, "Delete"}
};
