#include "win32.h" // IWYU pragma: keep

// ----------------------
// Keymap Win32 Modifiers
// ----------------------

static const nogui_keycode_t win32_keymap_table[256];
nogui_keycode_t win32_keymap_lookup(WPARAM wParam) {
    return win32_keymap_table[wParam];
}

nogui_keymask_t win32_keymask_lookup() {
    nogui_keymask_t mods = 0;

    // Check Key Modifiers
    if (GetKeyState(VK_SHIFT) & 0x8000)
        mods |= Mod_Shift;
    if (GetKeyState(VK_CONTROL) & 0x8000)
        mods |= Mod_Control;
    if (GetKeyState(VK_MENU) & 0x8000)
        mods |= Mod_Alt;

    // Check CapsLock & NumLock Status
    if (GetKeyState(VK_CAPITAL) & 1)
        mods |= Mod_Status_Caps;
    if (GetKeyState(VK_NUMLOCK) & 1)
        mods |= Mod_Status_Numpad;

    // Return Modifiers
    return mods;
}

// ---------------------------
// Keymap Win32 UTF8 Character
// ---------------------------

int win32_keycode_utf8(WCHAR wide, CHAR* buffer, int size) {
    size = WideCharToMultiByte( // Convert UTF16 to UTF8
        CP_UTF8, 0, &wide, 1, buffer, size, NULL, NULL);
    
    // Apply Null-terminated
    buffer[size] = '\0';
    return size;
}

// -------------------------------
// Keymap Win32 Native Translation
// Generated by keymap/keymap.py
// -------------------------------

static const nogui_keycode_t win32_keymap_table[256] = {
  [0] = NK_Unknown,
  [48] = NK_0,
  [49] = NK_1,
  [50] = NK_2,
  [51] = NK_3,
  [52] = NK_4,
  [53] = NK_5,
  [54] = NK_6,
  [55] = NK_7,
  [56] = NK_8,
  [57] = NK_9,
  [65] = NK_A,
  [66] = NK_B,
  [67] = NK_C,
  [68] = NK_D,
  [69] = NK_E,
  [70] = NK_F,
  [71] = NK_G,
  [72] = NK_H,
  [73] = NK_I,
  [74] = NK_J,
  [75] = NK_K,
  [76] = NK_L,
  [77] = NK_M,
  [78] = NK_N,
  [79] = NK_O,
  [80] = NK_P,
  [81] = NK_Q,
  [82] = NK_R,
  [83] = NK_S,
  [84] = NK_T,
  [85] = NK_U,
  [86] = NK_V,
  [87] = NK_W,
  [88] = NK_X,
  [89] = NK_Y,
  [90] = NK_Z,
  [VK_BACK] = NK_Backspace,
  [VK_TAB] = NK_Tab,
  [VK_RETURN] = NK_Return,
  [VK_SHIFT] = NK_Shift_L,
  [VK_CONTROL] = NK_Control_L,
  [VK_MENU] = NK_Alt_L,
  [VK_PAUSE] = NK_Pause,
  [VK_CAPITAL] = NK_Caps_Lock,
  [VK_ESCAPE] = NK_Escape,
  [VK_SPACE] = NK_Space,
  [VK_PRIOR] = NK_Page_Up,
  [VK_NEXT] = NK_Page_Down,
  [VK_END] = NK_End,
  [VK_HOME] = NK_Home,
  [VK_LEFT] = NK_Left,
  [VK_UP] = NK_Up,
  [VK_RIGHT] = NK_Right,
  [VK_DOWN] = NK_Down,
  [VK_SELECT] = NK_Select,
  [VK_PRINT] = NK_Print,
  [VK_EXECUTE] = NK_Execute,
  [VK_SNAPSHOT] = NK_Print,
  [VK_INSERT] = NK_Insert,
  [VK_DELETE] = NK_Delete,
  [VK_HELP] = NK_Help,
  [VK_LWIN] = NK_Super_L,
  [VK_RWIN] = NK_Super_R,
  [VK_APPS] = NK_Menu,
  [VK_NUMPAD0] = NKPad_0,
  [VK_NUMPAD1] = NKPad_1,
  [VK_NUMPAD2] = NKPad_2,
  [VK_NUMPAD3] = NKPad_3,
  [VK_NUMPAD4] = NKPad_4,
  [VK_NUMPAD5] = NKPad_5,
  [VK_NUMPAD6] = NKPad_6,
  [VK_NUMPAD7] = NKPad_7,
  [VK_NUMPAD8] = NKPad_8,
  [VK_NUMPAD9] = NKPad_9,
  [VK_MULTIPLY] = NKPad_Multiply,
  [VK_ADD] = NKPad_Add,
  [VK_SEPARATOR] = NKPad_Separator,
  [VK_SUBTRACT] = NKPad_Subtract,
  [VK_DECIMAL] = NKPad_Decimal,
  [VK_DIVIDE] = NKPad_Divide,
  [VK_F1] = NK_F1,
  [VK_F2] = NK_F2,
  [VK_F3] = NK_F3,
  [VK_F4] = NK_F4,
  [VK_F5] = NK_F5,
  [VK_F6] = NK_F6,
  [VK_F7] = NK_F7,
  [VK_F8] = NK_F8,
  [VK_F9] = NK_F9,
  [VK_F10] = NK_F10,
  [VK_F11] = NK_F11,
  [VK_F12] = NK_F12,
  [VK_NUMLOCK] = NK_Num_Lock,
  [VK_SCROLL] = NK_Scroll_Lock,
  [VK_LSHIFT] = NK_Shift_L,
  [VK_RSHIFT] = NK_Shift_R,
  [VK_LCONTROL] = NK_Control_L,
  [VK_RCONTROL] = NK_Control_R,
  [VK_LMENU] = NK_Alt_L,
  [VK_RMENU] = NK_AltGr,
  [VK_OEM_1] = NK_Semicolon,
  [VK_OEM_PLUS] = NK_Plus,
  [VK_OEM_COMMA] = NK_Comma,
  [VK_OEM_MINUS] = NK_Minus,
  [VK_OEM_PERIOD] = NK_Period,
  [VK_OEM_2] = NK_Question,
  [VK_OEM_3] = NK_Tilde,
  [VK_OEM_4] = NK_BracketLeft,
  [VK_OEM_5] = NK_Backslash,
  [VK_OEM_6] = NK_BracketRight,
  [VK_OEM_7] = NK_Apostrophe
};
